const CharacterList = [
  {
    id: 1,
    name: 'Mario',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 2,
    name: 'Luigi',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 3,
    name: 'Peach',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 4,
    name: 'Bowser',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 5,
    name: 'Yoshi',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 6,
    name: 'Rosalina & Luma',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 7,
    name: 'Donkey Kong',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 8,
    name: 'Diddy Kong',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 9,
    name: 'Link',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 10,
    name: 'Zelda',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 11,
    name: 'Sheik',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 12,
    name: 'Toon Link',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 13,
    name: 'Samus',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 14,
    name: 'Zero Suit Samus',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 15,
    name: 'Pit',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 16,
    name: 'Palutena',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 17,
    name: 'Marth',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 18,
    name: 'Ike',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 19,
    name: 'Robin',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 20,
    name: 'Kirby',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 21,
    name: 'King Dedede',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 22,
    name: 'Meta Knight',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 23,
    name: 'Little Mac',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 24,
    name: 'Fox',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 25,
    name: 'Pikachu',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 26,
    name: 'Charizard',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 27,
    name: 'Lucario',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 28,
    name: 'Greninja',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 29,
    name: 'Captain Falcon',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 30,
    name: 'Villager',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 31,
    name: 'Olimar',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 32,
    name: 'Wii Fit Trainer',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 33,
    name: 'Shulk',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 34,
    name: 'Pac-Man',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 35,
    name: 'Mega Man',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 36,
    name: 'Sonic',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 37,
    name: 'Mii Fighters',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 38,
    name: 'Ness',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 39,
    name: 'Falco',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 40,
    name: 'Wario',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 41,
    name: 'Lucina',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 42,
    name: 'Dark Pit',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 43,
    name: 'Dr. Mario',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 44,
    name: 'R.O.B.',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 45,
    name: 'Ganondorf',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 46,
    name: 'Mr. Game & Watch',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 47,
    name: 'Bowser Jr.',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 48,
    name: 'Duck Hunt',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 49,
    name: 'Jigglypuff',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 50,
    name: 'Mewtwo',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 51,
    name: 'Lucas',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 52,
    name: 'Roy',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 53,
    name: 'Ryu',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 54,
    name: 'Cloud',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 55,
    name: 'Corrin',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  },
  {
    id: 56,
    name: 'Bayonetta',
    media: [],
    nicknames: [],
    enabled: true,
    played: false,
    randomOrder: -1,
    websites: [],
    discord: {},
    moves: []
  }
];
export default CharacterList;
